# Generated by Django 6.0.7 on 2026-07-20 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0002_ordonnance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=200)),
                ('posologie', models.TextField()),
                ('quantite', models.IntegerField()),
                ('frequence', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=100)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.ordonnance')),
            ],
        ),
    ]
