# Generated by Django 6.0.7 on 2026-07-20 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0005_rendezvous'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_medecin', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
