# Generated by Django 6.0.7 on 2026-07-20 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0006_dossiermedical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_examen', models.DateTimeField()),
                ('type_examen', models.CharField(max_length=100)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.consultation')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_medecin', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
