# Generated by Django 6.0.7 on 2026-07-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0007_examen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultatExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.TextField()),
                ('date_resultat', models.DateTimeField(auto_now_add=True)),
                ('interpretation', models.TextField()),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.examen')),
            ],
        ),
    ]
