# Generated by Django 6.0.7 on 2026-07-20 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0008_resultatexamen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('type_chambre', models.CharField(max_length=50)),
                ('capacite', models.IntegerField()),
                ('disponibilite', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField()),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField()),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.chambre')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations_medecin', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
