# Generated by Django 6.0.7 on 2026-07-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0011_paiement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LigneOrdonnance',
        ),
    ]
