# Generated by Django 6.0.6 on 2026-07-22 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0012_delete_ligneordonnance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='medecin_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_suivis', to=settings.AUTH_USER_MODEL),
        ),
    ]
