# Generated by Django 6.0.7 on 2026-07-23 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0014_chatmessage_signalementmedecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='reponse_medecin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('answered', 'Répondue'), ('rejected', 'Rejetée')], default='pending', max_length=20),
        ),
    ]
