# Generated by Django 6.0.7 on 2026-08-01 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0016_medecin_emploitempsmedecin_emploidutemps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hopital.consultation'),
        ),
    ]
