# Generated by Django 6.0.7 on 2026-08-01 00:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0017_alter_examen_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances_medecin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='hopital.consultation'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='hopital.medicament'),
        ),
    ]
