# Generated by Django 6.0.7 on 2026-08-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0018_ordonnance_date_creation_ordonnance_medecin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='quantite_disponible',
            field=models.IntegerField(default=0),
        ),
    ]
