# Generated by Django 6.0.7 on 2026-08-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0020_ligneordonnance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='details_paiement',
            field=models.TextField(blank=True, default=''),
        ),
    ]
