# Generated by Django 6.0.6 on 2026-08-04 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0021_paiement_details_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploidutemps',
            name='medecin',
            field=models.ForeignKey(limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to=settings.AUTH_USER_MODEL),
        ),
    ]
