# Generated by Django 6.0.6 on 2026-08-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0026_alerteurgence_antecedentsmedicaux_auditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
    ]
