from django.urls import path
from .views import (
    index, hboard, stock_medicaments, ordonnances_view, inscription, medecin_list, connexion, 
    login_view, logout_view, register_view,
    saveinscription, saveconnexion, compte_parametres, chat_with_doctor, chat_message_action, chat_bulk_delete, chat_call_delete, chat_bulk_delete_calls, chat_inbox, patient_detail,
    create_video_call, video_call, video_call_invitations, video_call_participants, video_call_participant_action, video_call_signals,
    patient_consultation, patient_rendez_vous, patient_ordonnances, patient_factures, medecin_rendez_vous, medecin_patients, medecin_ordonnances, secretaire_ordonnances, secretaire_factures, medecin_exam_reports, medecin_exam_report_action, medecin_consultation, medecin_planning, view_doctor_planning,
    download_ordonnance_pdf, download_facture_pdf, set_specialite, secretaire_gestion_hospitaliere,
    secretaire_hospitalisations_en_cours,
    staff_rendez_vous, staff_consultations, staff_patients,
    staff_exam_reports,
)

# Les routes sont regroupées par domaine pour conserver une lecture rapide.
urlpatterns = [
    path('', index, name='index'),
    path('hboard/', hboard, name='hboard'),
    path('stock-medicaments/', stock_medicaments, name='stock_medicaments'),
    path('ordonnances/', ordonnances_view, name='ordonnances_view'),
    path('ordonnance/<int:ordonnance_id>/pdf/', download_ordonnance_pdf, name='download_ordonnance_pdf'),
    path('facture/<int:facture_id>/pdf/', download_facture_pdf, name='download_facture_pdf'),
    path('consultation/patient/', patient_consultation, name='patient_consultation'),
    path('rendez-vous/patient/', patient_rendez_vous, name='patient_rendez_vous'),
    path('ordonnances/patient/', patient_ordonnances, name='patient_ordonnances'),
    path('factures/patient/', patient_factures, name='patient_factures'),
    path('rendez-vous/medecin/', medecin_rendez_vous, name='medecin_rendez_vous'),
    path('patients/medecin/', medecin_patients, name='medecin_patients'),
    path('ordonnances/medecin/', medecin_ordonnances, name='medecin_ordonnances'),
    path('ordonnances/secretaire/', secretaire_ordonnances, name='secretaire_ordonnances'),
    path('factures/secretaire/', secretaire_factures, name='secretaire_factures'),
    path('comptes-rendus/medecin/', medecin_exam_reports, name='medecin_exam_reports'),
    path('compte-rendu/<int:report_id>/<str:action>/', medecin_exam_report_action, name='medecin_exam_report_action'),
    path('consultation/medecin/', medecin_consultation, name='medecin_consultation'),
    path('planning/medecin/', medecin_planning, name='medecin_planning'),
    path('planning/medecin/<int:doctor_id>/', view_doctor_planning, name='view_doctor_planning'),
    path('inscription/', inscription, name='inscription'),
    path('connexion/', connexion, name='connexion'),
    path('saveinscription/', saveinscription, name='saveinscription'),
    path('saveconnexion/', saveconnexion, name='saveconnexion'),
    path('register_view/', register_view, name='register_view'),
    path('login_view/', login_view, name='login_view'),
    path('logout_view/', logout_view, name='logout_view'),
    path('parametres/', compte_parametres, name='parametres'),
    path('chat/doctor/<int:doctor_id>/', chat_with_doctor, name='chat_with_doctor'),
    path('chat/message/<int:message_id>/<str:action>/', chat_message_action, name='chat_message_action'),
    path('chat/messages/delete/', chat_bulk_delete, name='chat_bulk_delete'),
    path('chat/call/<int:call_id>/delete/', chat_call_delete, name='chat_call_delete'),
    path('chat/calls/delete/', chat_bulk_delete_calls, name='chat_bulk_delete_calls'),
    path('chat/', chat_inbox, name='chat_inbox'),
    path('video-call/create/', create_video_call, name='create_video_call'),
    path('video-call/<uuid:room_id>/', video_call, name='video_call'),
    path('video-call/<uuid:room_id>/participants/', video_call_participants, name='video_call_participants'),
    path('video-call/invitations/', video_call_invitations, name='video_call_invitations'),
    path('video-call/<uuid:room_id>/participants/action/', video_call_participant_action, name='video_call_participant_action'),
    path('video-call/<uuid:room_id>/signals/', video_call_signals, name='video_call_signals'),
    path('patient/<int:patient_id>/', patient_detail, name='patient_detail'),
    path('medecin/', medecin_list, name='medecin-list'),
    path('medecin/set-specialite/<int:medecin_id>/', set_specialite, name='set_specialite'),
    path('medecin/set-specialite/', set_specialite, name='set_specialite_self'),
    path('secretaire/gestion-hospitaliere/', secretaire_gestion_hospitaliere, name='secretaire_gestion_hospitaliere'),
    path('secretaire/hospitalisations-en-cours/', secretaire_hospitalisations_en_cours, name='secretaire_hospitalisations_en_cours'),
    path('gestion/rendez-vous/', staff_rendez_vous, name='staff_rendez_vous'),
    path('gestion/consultations/', staff_consultations, name='staff_consultations'),
    path('gestion/patients/', staff_patients, name='staff_patients'),
    path('gestion/comptes-rendus-examens/', staff_exam_reports, name='staff_exam_reports'),

]